#!/bin/sh
for file in "/etc/profile" "$HOME/.profile" "/etc/yprofile" "$HOME/.yprofile"; do
    if [ -f "$file" ]; then
        . "$file"
    fi
done

eval "$(ssh-agent)"
export XDG_CURRENT_DESKTOP=wlroots

# if command -v dbus-update-activation-environment >/dev/null; then
#   dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=dwl
# fi
# if command -v systemctl >/dev/null; then
#   systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=dwl
# fi

/usr/local/bin/dwl
