#!/bin/sh
for file in "/etc/profile" "$HOME/.profile" "/etc/yprofile" "$HOME/.yprofile"; do
    if [ -f "$file" ]; then
        . "$file"
    fi
done

eval "$(ssh-agent)"

# Run all system xinitrc shell scripts
# xinitdir="/etc/X11/xinit/xinitrc.d"
# if [ -d "$xinitdir" ]; then
#     for script in $xinitdir/*; do
#         if [ -x "$script" -a ! -d "$script" ]; then
#             . "$script"
#         fi
#     done
# fi

/usr/local/bin/dwl
